version: "3.8"

services:
  sqlchat:
    build:
      context: .
    container_name: sqlchat
    platform: linux/amd64
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-$(openssl rand -hex 5)}
      OPENAI_API_KEY: empty
      OPENAI_API_ENDPOINT: http://192.168.1.2:11434/api/generate
      NEXT_PUBLIC_USE_DATABASE: false
    ports:
      - "3000:3000"
    hostname: 0.0.0.0
    restart: always
